### PR TITLE
Updated command syntax

### PR DESCRIPTION
**Pull request by dogversioning**
This PR makes the following updates:
- Slightly changes the formatting for the python command
- Adds a note about OS-specific formatting

### CODE REVIEW

**Comment by dogversioning** [comment]
@yuj sorry for the delay on this - tested this on a mac and a windows machine and I believe this is working, but please verify and let me know.

n.b. - i still don't see this in the available packages in package control on windows- there might be a change required on the package-control-contrib side for this?

**Comment by yuj** [comment]
Thanks for the PR. I am merging it.

For the Windows support, I'll try to address on the package-control-contrib side.

**Comment by yuj** [comment]
@dogversioning I've tested v0.2.1 on Ubuntu and Mac that are available to me, and it works on both platforms.
I've also made a change to package-control so the package is now available to all 3 major OS's.

**Comment by dogversioning** [comment]
@yuj perf, I've verified it's available and working on Windows as well.

**Pull request merged**
